type BoxClassProps = {
  languageimage: string;
  alt: string;
  image: string;
  name: string;
  jobtitle: string;
  rating: string;
  skills: string;
  followers: string;
};

const items: BoxClassProps[] = [
  {
    languageimage: "/Website/Tutoring/typescript-background.png",
    alt: "TypeScript",
    image: "/Website/About-Us/ejmenbusiness.png",
    name: "Ejmen Ramic",
    jobtitle: "QA Developer",
    rating: "5/5",
    skills: "Playwright, Typescript",
    followers: "23k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
  {
    languageimage: "/Website/Tutoring/python-background.png",
    alt: "Python",
    image: "/Website/About-Us//duckbusiness.jpg",
    name: "Maimul Hoque",
    rating: "5/5",
    jobtitle: "Backend Developer",
    skills: "Python, Next JS",
    followers: "49k",
  },
];

export default items;
